#!/bin/sh
d=/home/peterc/src/work/E_and_D//BoM-AutomatedWeatherStations/Half_hourly_data/
F=HM01X_Data_066037_999999998661926.txt #sydney airport
F=HM01X_Data_066062_999999998661926.txt #Observatory Hill

D=$d$F
{
    cat <<\EOF
set datafile separator ","
set timefmt '%d:%H:%M'
set format x '%H'
set xdata time
set style line 1 lw 3
set style line 2 lw 3
set ytics nomirror
set title "Sydney Hailstorm 1999-05-14"
set y2tics
set y2label "mBar"
set ylabel "%RH"
set yrange [0:100]
plot '-' using 1:2 with lines ls 1 title "relative humidity", '-' using 1:3 axes x1y2 title 'mslp (mBar)' with lines ls 2

EOF
    awk -F',' '/1999,05,1[45],/ { print $5 ":" $6 ":" $7 "," $21 "," $33 }' $D
    echo e
    awk -F',' '/1999,05,1[45],/ { print $5 ":"  $6 ":" $7 "," $21 "," $33 }' $D

} | gnuplot -persist

#plot '$D' using (($3-1999)*100000000+$4*1000000+$5*10000+$6*100+$7):33:xticlabels(strcol(6).':'.strcol(7)) title '1999-05-14 mslp (mBar)' with lines 
